# Imports

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns

In [16]:
plt.style.use('ggplot')
pd.options.display.max_columns = 200

In [7]:
df = pd.read_csv("data/oil_consumption.csv", index_col="index")

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14628 entries, 0 to 14627
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Development Name    14628 non-null  object
 1   Borough             14628 non-null  object
 2   Account Name        14628 non-null  object
 3   Location            962 non-null    object
 4   Meter AMR           14073 non-null  object
 5   Meter Scope         22 non-null     object
 6   TDS #               14628 non-null  int64
 7   EDP                 14628 non-null  int64
 8   RC Code             14628 non-null  object
 9   Funding Source      13106 non-null  object
 10  AMP #               12490 non-null  object
 11  Vendor Name         14628 non-null  object
 12  UMIS BILL ID        14628 non-null  int64
 13  Revenue Month       14628 non-null  object
 14  Service Start Date  14628 non-null  object
 15  Service End Date    14628 non-null  object
 16  # days              14628 non-null  int64
 17  Meter Number        14628 non-null  object
 18  Estimated           14628 non-null  object
 19  Current Charges     14628 non-null  float64
 20  Consumption (GAL)   14628 non-null  float64
dtypes: float64(2), int64(4), object(15)
memory usage: 2.5+ MB

In [9]:
df.shape

(14628, 21)

In [17]:
df.head()

,Development Name,Borough,Account Name,Location,Meter AMR,Meter Scope,TDS #,EDP,RC Code,Funding Source,AMP #,Vendor Name,UMIS BILL ID,Revenue Month,Service Start Date,Service End Date,# days,Meter Number,Estimated,Current Charges,Consumption (GAL)
index,,,,,,,,,,,,,,,,,,,,,
0,ADAMS,BRONX,ADAMS,NaN,Not Applicable,NaN,118,248,B011800,FEDERAL,NY005001180P,"S.J. Fuel Co., Inc.",2897085,2010-01,12/24/2009,01/26/2010,33,395416152700002-OIL,N,303.47,148.0
1,ADAMS,BRONX,ADAMS,NaN,Not Applicable,NaN,118,248,B011800,FEDERAL,NY005001180P,"S.J. Fuel Co., Inc.",2897086,2010-02,01/26/2010,02/25/2010,30,395416152700002-OIL,N,504.41,246.0
2,ADAMS,BRONX,ADAMS,NaN,Not Applicable,NaN,118,248,B011800,FEDERAL,NY005001180P,"S.J. Fuel Co., Inc.",2897087,2010-03,02/25/2010,03/26/2010,29,395416152700002-OIL,N,200.94,98.0
3,ADAMS,BRONX,ADAMS,NaN,Not Applicable,NaN,118,248,B011800,FEDERAL,NY005001180P,"S.J. Fuel Co., Inc.",2897088,2010-05,04/26/2010,05/24/2010,28,395416152700002-OIL,N,789.42,385.0
4,ADAMS,BRONX,ADAMS,NaN,Not Applicable,NaN,118,248,B011800,FEDERAL,NY005001180P,"S.J. Fuel Co., Inc.",2897089,2010-06,05/24/2010,06/23/2010,30,395416152700002-OIL,N,488.01,238.0